spring:
  application:
    name: loginServer

  datasource:
    url: "jdbc:mariadb://localhost:3306/server"
    username: root
    password: "01102000"
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    user:
      name: son
      password: "01102000"